server.port=8084

spring.datasource.url=${DATASOURCE.URL}
spring.datasource.username=${DATASOURCE.USERNAME}
spring.datasource.password=${DATASOURCE.PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT.SECRET}

razorpay.key=${RAZORPAY.KEY_ID}
razorpay.secret=${RAZORPAY.KEY_SECRET}


spring.mail.host=${MAIL.HOST}
spring.mail.port=${MAIL.PORT}
spring.mail.username=${MAIL.USERNAME}
spring.mail.password=${MAIL.PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
